apiVersion: 1

datasources:
  - name: Prometheus
    uid: efyig383hrxmoa
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Tempo
    uid: cfyig15ra28zka
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
